get.bicseq.chr <- function(reftype='b37') {
  valid_reftype = c('b37', 'ucsc')
  if (! reftype %in% valid_reftype) stop(paste(sep=' ', reftype, 'is an invalid reftype'))
  if (reftype == 'ucsc') {
    return(
      c(
        'chr1',
        'chr2',
        'chr3',
        'chr4',
        'chr5',
        'chr6',
        'chr7',
        'chr8',
        'chr9',
        'chr10',
        'chr11',
        'chr12',
        'chr13',
        'chr14',
        'chr15',
        'chr16',
        'chr17',
        'chr18',
        'chr19',
        'chr20',
        'chr21',
        'chr22',
        'chrX',
        'chrY'
        )
      )
   } else if (reftype == 'b37') {
    return(
      c(
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        'X',
        'Y'
        )
      )
    }
  }
